version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins:2.326
    container_name: 'jenkins'
    restart: always
    ports:
      - '80:8080'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
    logging:
      options:
        max-size: '300m'
        max-file: '5'
volumes:
  jenkins_data:
    driver: local
