version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins:2.326
    container_name: 'jenkins'
    restart: always
    ports:
      - '80:8080'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - '/usr/local/bin:/home/nqd/workspace/verik/cd/jenkins-docker-compose/bin'
      - "/var/run/docker.sock:/var/run/docker.sock"
    logging:
      options:
        max-size: '300m'
        max-file: '5'
volumes:
  jenkins_data:
    driver: local
