version: '2'

services:
  jenkins:
    container_name: 'jenkins'
    image: jenkins/jenkins:2.326
    ports:
      - '80:8080'
    environment:
      - JENKINS_PASSWORD=123456@Xx
    volumes:
      - 'jenkins_data:/opt/jenkins'

volumes:
  jenkins_data:
    driver: local
